### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by RJ722** [C-Aniruddh/realtime_object_recognition#1]
I had a hard time installing dependencies by hand. I can raise a PR if needed. Dependencies are:
```
imutils
opencv-python
numpy
request
```

One of the dependencies of `request` - `public` is broken because of missing README (Actually, it was renamed to `README.md` from `README.rst`), I had the following workaround:
```
git clone https://github.com/russianidiot/public.py.git
cd public.py
mv README.md README.rst
pip install .
```
and then normal installation

Also, it would be helpful if you had already mentioned `python3` somewhere.

**Comment by C-Aniruddh** [comment]
I pull request would be helpful! Thanks for pointing it out.
